### PR TITLE
Set num threads in onnx inference session

### PR DESCRIPTION
**Pull request by timbmg**
# What does this PR do?
Make ONNX models compatible with using a subset of CPUs.
1. Fixes bug where SessionOptions were not passed to InferenceSession
2. Sets num threads in session options configurable by `CPU_COUNT` variable.

### CODE REVIEW

**Comment by timbmg** [comment]
@Rachneet can you have a quick look that this makes sense?:)

**Comment by Rachneet** [comment]
Okay great. So this will select the num cpus based on CPU_COUNT and otherwise default to 1 or num_cpu//8, right?
How much improvement did you get?

**Comment by timbmg** [comment]
In #449 I have changed that every model only has access to 1/8th of the CPUs. However, this did not seem to work with ONNX models. I have to set this parameter in the SessionOptions. There I also noticed that the SessionOptions was not passed to the InferenceSession. So I was wondering if that was intended or not.

**Comment by Rachneet** [comment]
> Right.
> 
> In #449 I have changed that every model has by default only access to 1/8th of the CPUs. However, this did not seem to work with ONNX models. I have to set this parameter in the SessionOptions. There I also noticed that the SessionOptions was not passed to the InferenceSession. So I was wondering if that was intended or not.

Okay. This sounds good. There was no particular intention of not including session options. The idea is that we set them based on our requirements and it was just using defaults.

LGTM

**Pull request merged**
