### PR TITLE
Skill args UI

### PR DESCRIPTION
**Pull request by HaritzPuerto**
image

### CODE REVIEW

**Comment by timbmg** [comment]
cool! We could also improve upon this by adding an endpoint to the skill-manager that returns the fields that a skill can take. What do you think?

**Comment by HaritzPuerto** [comment]
> cool! We could also improve upon this by adding an endpoint to the skill-manager that returns the fields that a skill can take. What do you think?

yes! definitely! we could do that! but the UI would be a bit less friendly? I mean right now the user cannot write an `adapter` unless they write a `base model`. Same with `index` and `datastore`. (I'm using the disabled parameter in the input tags) If we use this endpoint, we would lose this logic, right?

**Comment by HaritzPuerto** [comment]
@kwang2049 datastores and indices could be a dropdown so that the user doesn't have to know if advance the exact names. I guess I could have an endpoint to the datastores API that gives me the names of the available datastores and indices

**Comment by HaritzPuerto** [comment]
Datastores and indexes are retrieved with the API and given as options in a select. However, the logic gets tricky... @kwang2049, why is BM25 not included as an index ? (the retrieve index API does not return it, but afaik, it's the default index for all document collections (because we are using elasticsearch) if we want to use BM25, we do not need to use the index param, but this is not straightforward for a user, so I had to put some conditions that are not that easy to understand... so that the user can see BM25 and select it.

I think after the vacations, we need to discuss if we can include BM25 as an index (BM25 is an index after all)
image

**Pull request merged**
