### PR TITLE
Model api v3

### PR DESCRIPTION
**Pull request by Rachneet**
# What does this PR do?
New version of model API where every model type has its own docker image eg, transformer, onnx, sentence-transformer
-->

## Who can review?
@timbmg

 -->

### CODE REVIEW

**Comment by timbmg** [comment]
Could you resolve the conflicts please?

**Comment by timbmg** [comment]
I did some refactoring in the [model-api-v3-refactor](https://github.com/UKP-SQuARE/square-core/tree/model-api-v3-refactor) branch. Please review them and if you agree merge them into this branch.

**Comment by Rachneet** [comment]
Hey Tim, this is ready for merge. Please have a look when you can.

**Comment by timbmg** [comment]
`docker-compose.ytt.yaml` does not use the model-v3 services. Please update the file.

**Review by timbmg — APPROVED** [review]

**Comment by HaoZ-Work** [comment]
> I just tested it again, and it seems custom models do not work. Could you please check? It's currently deployed on the test-vm. It seems some problem between the main_model and the model. The worker shows no log of receiving the request. image

> Hi Tim, i checked it. It works. The path of enter point  is `/api/mian/model_name` instead of `/api/model_name`

**Pull request merged**
